<html>
<head>
<script type="text/javascript">
function okno_zamknij_skomra()
{
window.close()
}
</script>
</head>
<body>
======================Początek opisu teorii===================================
Rodzaje okienek:
 Okienko alert – wyświetlająca okienko dialogowe z informacją i przyciskiem OK,
 Okienko prompt – generująca okno, w którym użytkownik może wpisać wartość, zwracaną następnie do programu.
 Okienko confirm służy do tego, aby użytkownik coś potwierdził (stąd nazwa confirm).
Konwersji liczb.
Wczytanie zmiennej z użyciem prompt wykonywane jest jako ciąg znaków dlatego konieczna jest konwersji z ciągu znaków na wartości liczbowe aby wykonywac obliczenia.
parseFloat(zmienna) - konwersja zmiennej do typu float
parseInt(zmienna) - konwersja zmiennej do typu int (liczbowego)
toString(zmienna) - konwersja zmiennej do typu łańcuchowego
======================= Koniec opisu teorii ======================================
<input type="button" value="zamknij okno" onclick="okno_zamknij()"/>
</body>
</html>
